/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geni_logiciel_projet1;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.*;

public abstract class App {

    private final static Operativ operativ = new Operativ(0, 6, 0);
    private final static CommandControl command_control = new CommandControl();
    private final static PanelWindow window = new PanelWindow();

    public static void main(String[] args) {
        //Démarrage de la partie opérative
        operativ.start();

        //Appelle de la fenêtre
        SwingUtilities.invokeLater(() -> window.setVisible(true));
    }

    static void addDestination(Destination destination) {
        command_control.addDestination(destination);
    }

    static void addDestination(int destination) {
        command_control.addDestination(destination);
    }

    static void updateCurrentFloor (int current_floor) {
        updateCommandControlFloor(current_floor);
        updateLabelFloor(current_floor);
    }

    private static void updateLabelFloor(int current_floor) {
        window.updateLabelFloor(String.valueOf(current_floor));
    }

    private static void updateCommandControlFloor(int current_floor) {
        command_control.setCurrent_floor(current_floor);
    }

    static void updateLabelState(int state) {
        window.updateLabelState(state);
    }
}

