/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geni_logiciel_projet1;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.*;

import javax.swing.*;

public class App {

    final static Elevator elevator = new Elevator();
    final static PanelWindow window = new PanelWindow();

    public static void main(String[] args) {

        //Appelle de la fenêtre
        SwingUtilities.invokeLater(new Runnable(){
            public void run(){
                window.setVisible(true);
            }
        });

        TimerTask task = new TimerTask() {
            public void run() {
                elevator.run();
                updateLabel(String.valueOf(elevator.getCurrent_level()));
            }
        };
        Timer timer = new Timer();
        timer.schedule(task, 1000,1000);
    }

    final static void addDestination(int destination) {
        elevator.addDestination(destination);
    }

    final static void updateLabel(String newString) {
        window.updateLabel(newString);
    }
}

