/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geni_logiciel_projet1;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.*;

import javax.swing.*;

public class App {

    public static void main(String[] args) {

        //Appelle de la fenêtre
        SwingUtilities.invokeLater(new Runnable(){
            public void run(){
                PanelWindow window = new PanelWindow();
                window.setVisible(true);
            }
        });
      
        /* Elevator elevator = new Elevator();

        TimerTask task = new TimerTask() {
            public void run() {
                elevator.run();
            }
        };
        Timer timer = new Timer();
        timer.schedule(task, 1000,1000); */
    }
}

